kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-zookeeper-pv-claim
spec:
  storageClassName: nfs-client #manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
