apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-volume
spec:
  storageClassName: nfs-client #manual
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/zookeeper/
