apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  ports:
  - port: 30181
    targetPort: 30181
    nodePort: 30181
    protocol: TCP
  selector:
    app: zookeeper-app
  type: NodePort
