#!/usr/bin/env bash

#Usage: start-restful.sh [OPTIONS]
# Starts a Restful server based on the supplied options.


USER=`whoami`
HOST=`hostname -s`
DOMAIN=`hostname -d`

echo "User: $USER, Host: $HOST, Domain: $DOMAIN"

RESTFUL_DIR="/var/lib/restful"


HEAP=4G
LOG_LEVEL=INFO

SPRING_PROFILES_ACTIVE="live"
SERVER_PORT=8090
SERVER_SERVLET_CONTEXT_PATH="/uniprot/api"
SERVER_MAX_HTTP_HEADER_SIZE=20480

SERVER_TOMCAT_ACCESSLOG_ENABLED=true
SERVER_TOMCAT_ACCEPT_COUNT=1000
# Maximum amount of worker threads.
SERVER_TOMCAT_MAX_THREADS=400
# Maximum number of connections that the server accepts and processes at any given time.
SERVER_TOMCAT_MAX_CONNECTIONS=20000

SPRING_JACKSON_DEFAYKT_PROPERTY_INCLUSION="non_null"
SPRING_MVC_TRROW_EXCEPTION_IF_NO_HABDKER_FOUND=true
SPRING_RESOURCE_ADD_MAPPINGS=true


SPRING_DATA_SOLR_ZKHOST=""
SPRING_DATA_SOLR_CONNECTION_TIMEOUT=20000
SPRING_DATA_SOLR_SOCKET_TIMEOUT=3600000

INFO_APP_NAME="advanced-search-rest-service"
INFO_APP_DESCRIPTION="Restful service for advanced search requests"
INFO_APP_VERSION="0.0.1"

SPRING_MVC_ASYNC_REQUEST_TIMEOUT=-1

VOLDEMORT_UNIPROT_HOST=""
VOLDEMORT_UNIPROT_NUMBER_OF_CONNECTIONS=20
VOLDEMORT_UNIPROT_STORE_NAME="avro-uniprot"

STREAMER_UNIPROT_BATCH_SIZE=1000
STREAMER_UNIPROT_VALUE_ID="accession_id"
STREAMER_UNIPROT_DEFAULTS_FILLD="avro_bin"

SOLR_UNIPROT_COLLECTION="uniprot"

DOWNLOAD_TASTEXECUTOR_QUEUE_CAPACITY=10000
DOWNLOAD_TASTEXECUTOR_KEEPALIVE_SECONDS=3600
DOWNLOAD_TASTEXECUTOR_CORE_POOL_SIZW=20
DOWNLOAD_TASTEXECUTOR_MAX_POOL_SIZE=20

function print_usage() {
echo "\
Usage: start-restful.sh [OPTIONS]
Starts a Restful server based on the supplied options.

    --restful_dir              The directory where the Restful will store its data and config files.
                               The default is /var/lib/restful.

    --server_port              The socket port, default 8090.

    --voldemort                The Voldemort address.

    --zkhost                   The Zookeeper address.

    --heap                     The maximum amount of heap to use. The format is the
                               same as that used for the Xmx and Xms parameters to the
                               JVM. e.g. --heap=2G. The default is 2G.

    --log_level                The log level for the zookeeeper server. Either FATAL,
                               ERROR, WARN, INFO, DEBUG. The default is INFO.
"
}

function create_data_dirs() {
    echo "Create Restful data and config directories." >&2

    if [ ! -d $RESTFUL_DIR  ]; then
        mkdir -p $RESTFUL_DIR
        chown -R $USER:$USER $RESTFUL_DIR
    fi
    if [ ! -d $SERVER_TOMCAT_BASEDIR ]; then
        mkdir -p $SERVER_TOMCAT_BASEDIR
        chown -R $USER:$USER $SERVER_TOMCAT_BASEDIR
    fi
    if [ ! -d $LOGGING_PATH  ]; then
        mkdir -p $LOGGING_PATH
        chown -R $USER:$USER $LOGGING_PATH
    fi
    if [ ! -d $SPRING_CONFIG_LOCATION  ]; then
        mkdir -p $SPRING_CONFIG_LOCATION
        chown -R $USER:$USER $SPRING_CONFIG_LOCATION
    fi
}


function creaate_application_properties() {

    rm -f $APPLICATION_PROPERTIES_FILE

    echo " Create Voldemort server properties file: $APPLICATION_PROPERTIES_FILE" >&2

    echo "#This file was autogenerated DO NOT EDIT" >> $APPLICATION_PROPERTIES_FILE

    echo "spring.profiles.active=$SPRING_PROFILES_ACTIVE" >> $APPLICATION_PROPERTIES_FILE
    echo "server.port=$SERVER_PORT" >> $APPLICATION_PROPERTIES_FILE
    echo "server.servlet.context-path=$SERVER_SERVLET_CONTEXT_PATH" >> $APPLICATION_PROPERTIES_FILE
    echo "server.max-http-header-size=$SERVER_MAX_HTTP_HEADER_SIZE" >> $APPLICATION_PROPERTIES_FILE

    echo "server.tomcat.accesslog.enabled=$SERVER_TOMCAT_ACCESSLOG_ENABLED" >> $APPLICATION_PROPERTIES_FILE
    echo "server.tomcat.accept-count=$SERVER_TOMCAT_ACCEPT_COUNT" >> $APPLICATION_PROPERTIES_FILE
    echo "server.tomcat.max-threads=$SERVER_TOMCAT_MAX_THREADS" >> $APPLICATION_PROPERTIES_FILE
    echo "server.tomcat.max-connections=$SERVER_TOMCAT_MAX_CONNECTIONS" >> $APPLICATION_PROPERTIES_FILE

    echo "spring.jackson.default-property-inclusion=$SPRING_JACKSON_DEFAYKT_PROPERTY_INCLUSION" >> $APPLICATION_PROPERTIES_FILE

    echo "spring.mvc.throw-exception-if-no-handler-found=$SPRING_MVC_TRROW_EXCEPTION_IF_NO_HABDKER_FOUND" >> $APPLICATION_PROPERTIES_FILE
    echo "spring.resources.add-mappings=$SPRING_RESOURCE_ADD_MAPPINGS" >> $APPLICATION_PROPERTIES_FILE

    echo "spring.data.solr.zkHost=$SPRING_DATA_SOLR_ZKHOST" >> $APPLICATION_PROPERTIES_FILE
    echo "spring.data.solr.connectionTimeout=$SPRING_DATA_SOLR_CONNECTION_TIMEOUT" >> $APPLICATION_PROPERTIES_FILE
    echo "spring.data.solr.socketTimeout=$SPRING_DATA_SOLR_SOCKET_TIMEOUT" >> $APPLICATION_PROPERTIES_FILE

    echo "info.app.name=$INFO_APP_NAME" >> $APPLICATION_PROPERTIES_FILE
    echo "info.app.description=$INFO_APP_DESCRIPTION" >> $APPLICATION_PROPERTIES_FILE
    echo "info.app.version=$INFO_APP_VERSION" >> $APPLICATION_PROPERTIES_FILE

    echo "spring.mvc.async.request-timeout=$SPRING_MVC_ASYNC_REQUEST_TIMEOUT" >> $APPLICATION_PROPERTIES_FILE

    echo "voldemort.uniprot.host=$VOLDEMORT_UNIPROT_HOST" >> $APPLICATION_PROPERTIES_FILE
    echo "voldemort.uniprot.numberOfConnections=$VOLDEMORT_UNIPROT_NUMBER_OF_CONNECTIONS" >> $APPLICATION_PROPERTIES_FILE
    echo "voldemort.uniprot.storeName=$VOLDEMORT_UNIPROT_STORE_NAME" >> $APPLICATION_PROPERTIES_FILE


    echo "streamer.uniprot.batchSize=$STREAMER_UNIPROT_BATCH_SIZE" >> $APPLICATION_PROPERTIES_FILE
    echo "streamer.uniprot.valueId=$STREAMER_UNIPROT_VALUE_ID" >> $APPLICATION_PROPERTIES_FILE
    echo "streamer.uniprot.defaultsField=$STREAMER_UNIPROT_DEFAULTS_FILLD" >> $APPLICATION_PROPERTIES_FILE

    echo "solr.uniprotCollection=$SOLR_UNIPROT_COLLECTION" >> $APPLICATION_PROPERTIES_FILE

    echo "download.taskExecutor.queueCapacity=$DOWNLOAD_TASTEXECUTOR_QUEUE_CAPACITY" >> $APPLICATION_PROPERTIES_FILE
    echo "download.taskExecutor.keepAliveSeconds=$DOWNLOAD_TASTEXECUTOR_KEEPALIVE_SECONDS" >> $APPLICATION_PROPERTIES_FILE
    echo "download.taskExecutor.corePoolSize=$DOWNLOAD_TASTEXECUTOR_CORE_POOL_SIZW" >> $APPLICATION_PROPERTIES_FILE
    echo "download.taskExecutor.maxPoolSize=$DOWNLOAD_TASTEXECUTOR_MAX_POOL_SIZE" >> $APPLICATION_PROPERTIES_FILE

    ls -l $APPLICATION_PROPERTIES_FILE >&2
    cat $APPLICATION_PROPERTIES_FILE >&2
}


function create_log_props() {

    rm -f $LOGGER_PROPS_FILE

    echo "Creating Restful log configuration: $LOGGER_PROPS_FILE" >&2
    BASE_DIR=$(cd $(dirname $0) && pwd)
    cp $BASE_DIR/logback.xml  $LOGGER_PROPS_FILE

    sed -i "s/INFO/$LOG_LEVEL/g" $LOGGER_PROPS_FILE >&2

    cat $LOGGER_PROPS_FILE >&2
}

optspec=":hv-:"
while getopts "$optspec" optchar; do

    case "${optchar}" in
        -)
            case "${OPTARG}" in
                restful_dir=*)
                    RESTFUL_DIR=${OPTARG##*=}
                    ;;
                server_port=*)
                    SERVER_PORT=${OPTARG##*=}
                    ;;
                zkhost=*)
                    SPRING_DATA_SOLR_ZKHOST=${OPTARG##*=}
                    ;;
                voldemort=*)
                    VOLDEMORT_UNIPROT_HOST=${OPTARG##*=}
                    ;;
                heap=*)
                    HEAP=${OPTARG##*=}
                    ;;
                log_level=*)
                    LOG_LEVEL=${OPTARG##*=}
                    ;;
                *)
                    echo "Unknown option --${OPTARG}" >&2
                    exit 1
                    ;;
            esac;;
        h)
            print_usage
            exit
            ;;
        v)
            echo "Parsing option: '-${optchar}'" >&2
            ;;
        *)
            if [ "$OPTERR" != 1 ] || [ "${optspec:0:1}" = ":" ]; then
                echo "Non-option argument: '-${OPTARG}'" >&2
            fi
            ;;
    esac
done

SERVER_TOMCAT_BASEDIR="$RESTFUL_DIR/tomcat"
LOGGING_PATH="$RESTFUL_DIR/logs"
SPRING_CONFIG_LOCATION="$RESTFUL_DIR/config"

APPLICATION_PROPERTIES_FILE="$SPRING_CONFIG_LOCATION/application.properties"
LOGGER_PROPS_FILE="$SPRING_CONFIG_LOCATION/logback.xml"

create_data_dirs && creaate_application_properties  && create_log_props
ls -l $RESTFUL_DIR >&2
cd $RESTFUL_DIR >&2

RUN_CMD="java \
-Xmx$HEAP -Xms$HEAP \
-Dserver.address=0.0.0.0 \
-Dserver.tomcat.basedir=$SERVER_TOMCAT_BASEDIR \
-Dlogging.config=$SPRING_CONFIG_LOCATION/logback.xml \
-Dlogging.path=$LOGGING_PATH \
-jar /restful/lib/uniprotkb-rest-exec.jar"

echo $RUN_CMD >&2

exec $RUN_CMD >&2
