apiVersion: v1
kind: Service
metadata:
  name: nginx-website
spec:
  ports:
    - port: 30280
      targetPort: 80
      nodePort: 30280
      protocol: TCP
  selector:
    app: nginx-website
  type: NodePort

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-website
spec:
  serviceName: "nginx-website"
  replicas: 1
  selector:
    matchLabels:
      app: nginx-website
  template:
    metadata:
      labels:
        app: nginx-website
    spec:
      containers:
        - name: nginx-website
          image: guoyingqi/uniprot-website
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: uniprot-website
              mountPath: /var/log/uniprot-website
  volumeClaimTemplates:
    - metadata:
        name: uniprot-website
      spec:
        storageClassName: nfs-client
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
