apiVersion: v1
kind: Service
metadata:
  name: vd-hs
  labels:
    app: vd
spec:
  ports:
  - port: 2186
    name: socket
  - port: 2185
    name: http
  - port: 2187
    name: admin
  clusterIP: None
  selector:
    app: vd

---
apiVersion: v1
kind: Service
metadata:
  name: vd-cs
spec:
  ports:
    - port: 2186
      targetPort: 2186
      nodePort: 30186
      protocol: TCP
      name: socket
    - port: 2187
      targetPort: 2187
      nodePort: 30187
      protocol: TCP
      name: admin
    - port: 2185
      targetPort: 2185
      nodePort: 30185
      protocol: TCP
      name: http
  selector:
    app: vd
  type: NodePort

---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: vd-pdb
spec:
  selector:
    matchLabels:
      app: vd
  maxUnavailable: 1

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vd
spec:
  selector:
    matchLabels:
      app: vd
  serviceName: vd-hs
  replicas: 6 # should be the same as the number of servers for the start-voldemort scrsipts
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: vd
    spec:
      volumes:
        - name: nfs-share-volume-uniprot-vd
          nfs:
            server: hx-isi-srv-vlan157.ebi.ac.uk
            path: /ifs/public-r/rw/uniprot/voldemort_cloud/cloud1
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - vd
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: voldemort
          imagePullPolicy: Always
          image: "guoyingqi/voldemort"
          resources:
            requests:
              memory: "4Gi"
              cpu: "0.5"
          ports:
            - containerPort: 2186
              name: socket
            - containerPort: 2185
              name: http
            - containerPort: 2187
              name: admin
          command: # both the numbers of nodes and the number of partitions per node should be the same as the number of replicates
            - sh
            - -c
            - "start-voldemort.sh \
               --servers=6 \
               --partitions_per_node=6 \
               --log_level=INFO"
          readinessProbe:
            tcpSocket:
              port: 2185
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
              tcpSocket:
                port: 2185
              initialDelaySeconds: 15
              periodSeconds: 20
          volumeMounts:
            - name: nfs-share-volume-uniprot-vd
              mountPath: /var/lib/voldemort
      securityContext:
        runAsUser: 2796
        fsGroup: 1128

