apiVersion: v1
kind: PersistentVolume
metadata:
  name: solr-volume
spec:
  storageClassName: nfs-client #manual
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 200Gi
  hostPath:
    path: /data/solr
