apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: solr
spec:
  selector:
    matchLabels:
      app: solr-app # has to match .spec.template.metadata.labels
  serviceName: "solr-service-hs"
  replicas: 5
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: solr-app # has to match .spec.selector.matchLabels
    spec:
      volumes:
        - name: nfs-share-volume-uniprot
          nfs:
            server: hx-isi-srv-vlan157.ebi.ac.uk
            path: /ifs/public-r/rw/uniprot
      terminationGracePeriodSeconds: 60
      restartPolicy: Always
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - solr-app
              topologyKey: "kubernetes.io/hostname"
      containers:
        # https://hub.docker.com/_/solr
        # https://github.com/docker-solr/docker-solr
        - name: solr
          image: solr:8.2
          resources:
            limits:
              memory: "18Gi"
            requests:
              memory: "16Gi"
          volumeMounts:
            - name: solr-data
              mountPath: /store
            - name: nfs-share-volume-uniprot
              mountPath: /nfs-share-uniprot
          ports:
            - name: solr-port
              containerPort: 8983
          env:
            - name: POD_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SOLR_HOME
              valueFrom:
                configMapKeyRef:
                  name: solr-config
                  key: solrHome
            - name: SOLR_DATA_HOME
              valueFrom:
                configMapKeyRef:
                  name: solr-config
                  key: solrData
            - name: SOLR_PORT
              valueFrom:
                configMapKeyRef:
                  name: solr-config
                  key: solrPort
            - name: ZK_HOST
              valueFrom:
                configMapKeyRef:
                  name: solr-config
                  key: zkHost
            - name: SOLR_JAVA_MEM
              valueFrom:
                configMapKeyRef:
                  name: solr-config
                  key: javaMemory
            - name: SOLR_HOST
              value: "$(POD_HOST_NAME).solr-service-hs.$(POD_NAMESPACE).svc.cluster.local"
            - name: SOLR_LOGS_DIR
              valueFrom:
                configMapKeyRef:
                  name: solr-config
                  key: solrLogsDir
          readinessProbe:
            tcpSocket:
              port: 8983
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            tcpSocket:
              port: 8983
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 30
      initContainers:
        - name: init-solr-data
          image: busybox
          command:
          - "/bin/sh"
          - "-c"
          - "if [ ! -d $SOLR_DATA_HOME ] ; then mkdir -p $SOLR_DATA_HOME && chown -R 8983:8983 $SOLR_DATA_HOME ; else true; fi"
          env:
              - name: SOLR_DATA_HOME
                valueFrom:
                  configMapKeyRef:
                    name: solr-config
                    key: solrData
          volumeMounts:
            - name: solr-data
              mountPath: /store
        - name: init-solr-home
          image: busybox
          command:
          - "/bin/sh"
          - "-c"
          - "if [ ! -d $SOLR_HOME ] ; then mkdir -p $SOLR_HOME && chown -R 8983:8983 $SOLR_HOME ; else true; fi"
          env:
              - name: SOLR_HOME
                valueFrom:
                  configMapKeyRef:
                    name: solr-config
                    key: solrHome
          volumeMounts:
            - name: solr-data
              mountPath: /store
        - name: init-solr-logs
          image: busybox
          command:
          - "/bin/sh"
          - "-c"
          - "if [ ! -d $SOLR_LOGS_DIR ] ; then mkdir -p $SOLR_LOGS_DIR && chown 8983:8983 $SOLR_LOGS_DIR ; else true; fi"
          env:
              - name: SOLR_LOGS_DIR
                valueFrom:
                  configMapKeyRef:
                    name: solr-config
                    key: solrLogsDir
          volumeMounts:
            - name: solr-data
              mountPath: /store
        - name: init-solr-xml
          image: solr:8.2
          command:
          - "/bin/sh"
          - "-c"
          - "if [ ! -f $SOLR_HOME/solr.xml ] ; then cp /opt/solr/server/solr/solr.xml $SOLR_HOME/solr.xml;\
                         sed -i \"s/<solr>/<solr><str name='sharedLib'>\\/store\\/solr_home<\\/str>/g\" $SOLR_HOME/solr.xml ; else true; fi "
          env:
            - name: SOLR_HOME
              valueFrom:
                configMapKeyRef:
                  name: solr-config
                  key: solrHome
          volumeMounts:
            - name: solr-data
              mountPath: /store
  volumeClaimTemplates:
    - metadata:
        name: solr-data
      spec:
        storageClassName: local-storage
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 300Gi
        