apiVersion: v1
kind: Service
metadata:
  name: kb-rest-hs
  labels:
    app: kb-rest
spec:
  ports:
    - port: 8090
      name: http
  clusterIP: None
  selector:
    app: kb-rest

---
apiVersion: v1
kind: Service
metadata:
  name: kb-rest-http
spec:
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 30299
      protocol: TCP
  selector:
    app: kb-rest
  type: NodePort

---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: kb-rest-pdb
spec:
  selector:
    matchLabels:
      app: kb-rest
  maxUnavailable: 1

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kb-rest
spec:
  selector:
    matchLabels:
      app: kb-rest
  serviceName: kb-rest-hs
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: kb-rest
    spec:
      volumes:
        - name: nfs-share-volume-uniprot-kb-rest
          nfs:
            server: hx-isi-srv-vlan157.ebi.ac.uk
            path: /ifs/public-r/rw/uniprot/restful_cloud/kb
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - kb-rest
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: kubernetes-uniprotkb-rest
          imagePullPolicy: Always
          image: "guoyingqi/uniprotkb-rest"
          resources:
            requests:
              memory: "16Gi"
          ports:
            - containerPort: 8090
              name: http
          command:
            - sh
            - -c
            - "start-restful.sh \
                 --heap=14G \
                 --voldemort=tcp://vd-0.vd-hs.uniprot-web.svc.cluster.local:2186 \
                 --zkhost=zk-0.zk-hs.uniprot-web.svc.cluster.local:2181,zk-1.zk-hs.uniprot-web.svc.cluster.local:2181,zk-2.zk-hs.uniprot-web.svc.cluster.local:2181 \
                 --log_level=INFO"
          readinessProbe:
            tcpSocket:
              port: 8090
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8090
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - name: nfs-share-volume-uniprot-kb-rest
              mountPath: /var/lib/restful
      securityContext:
        runAsUser: 2796
        fsGroup: 1128
