apiVersion: v1
kind: Service
metadata:
  name: kb-rest-hs
  labels:
    app: kb-rest
spec:
  ports:
    - port: 8090
      name: http
  clusterIP: None
  selector:
    app: kb-rest

---
apiVersion: v1
kind: Service
metadata:
  name: kb-rest-http
spec:
  ports:
    - port: 30299
      targetPort: 8090
      nodePort: 30299
      protocol: TCP
  selector:
    app: kb-rest
  type: NodePort

---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: kb-rest-pdb
spec:
  selector:
    matchLabels:
      app: kb-rest
  maxUnavailable: 1

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kb-rest
spec:
  selector:
    matchLabels:
      app: kb-rest
  serviceName: kb-rest-hs
  replicas: 2
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: kb-rest
    spec:
      volumes:
        - name: miniodata
          persistentVolumeClaim:
            claimName: minio-pv-claim
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - kb-rest
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: kubernetes-uniprotkb-rest
          imagePullPolicy: Always
          image: "guoyingqi/uniprotkb-rest"
          resources:
            requests:
              memory: "16Gi"
          ports:
            - containerPort: 8090
              name: http
          command:
            - sh
            - -c
            - "start-restful.sh \
                 --heap=14G \
                 --voldemort=tcp://vd-0.vd-hs.uniprot.svc.cluster.local:2186 \
                 --zkhost=zk-0.zk-hs.uniprot.svc.cluster.local:2181,zk-1.zk-hs.uniprot.svc.cluster.local:2181,zk-2.zk-hs.uniprot.svc.cluster.local:2181 \
                 --ec_dir=/minio/restful/ff/ec/ \
                 --keyword_file=/minio/restful/ff/keywlist.txt \
                 --pathway_file=/minio/restful/ff/unipathway.txt \
                 --log_level=DEBUG"
          readinessProbe:
            tcpSocket:
              port: 8090
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8090
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - name: kb-rest-data
              mountPath: /var/lib/restful
            - name: miniodata
              mountPath: /minio
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
  volumeClaimTemplates:
    - metadata:
        name: kb-rest-data
      spec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
