
apiVersion: v1
kind: Service
metadata:
  name: uniprotkb-hs
  labels:
    app: uniprotkb
spec:
  ports:
    - port: 8090
      name: http
  clusterIP: None
  selector:
    app: uniprotkb
---

apiVersion: v1
kind: Service
metadata:
  name: uniprotkb-rest-http
spec:
  ports:
    - port: 30299
      targetPort: 8090
      nodePort: 30299
      protocol: TCP
  selector:
    app: uniprotkb
  type: NodePort

---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: uniprotkb-pdb
spec:
  selector:
    matchLabels:
      app: uniprotkb
  maxUnavailable: 1

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: uniprotkb
spec:
  selector:
    matchLabels:
      app: uniprotkb
  serviceName: uniprotkb-hs
  replicas: 2
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: uniprotkb
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - uniprotkb
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: kubernetes-uniprotkb-rest
          imagePullPolicy: Always
          image: "guoyingqi/uniprotkb-rest"
          resources:
            requests:
              memory: "5Gi"
              cpu: "0.5"
          ports:
            - containerPort: 8090
              name: http
          command:
            - sh
            - -c
            - "start-restful.sh \
          --voldemort=tcp://vd-0.vd-hs.default.svc.cluster.local:30186 \
          --zkhost=zk-0.zk-hs.default.svc.cluster.local:2181,zk-1.zk-hs.default.svc.cluster.local:2181,zk-2.zk-hs.default.svc.cluster.local:2181 \
          --log_level=DEBUG"
 #         readinessProbe:
 #           httpGet:
 #               path: /uniprot/api
 #              port: 8090
 #           initialDelaySeconds: 10
 #           timeoutSeconds: 5
 #         livenessProbe:
 #             httpGet:
 #               path: /uniprot/api
 #               port: 8090
 #             initialDelaySeconds: 10
 #             periodSeconds: 3
          volumeMounts:
            - name: restdata
              mountPath: /var/lib/restful
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
  volumeClaimTemplates:
    - metadata:
        name: restdata
      spec:
        storageClassName: nfs-client
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
