apiVersion: v1
kind: Service
metadata:
  name: support-data-rest-hs
  labels:
    app: support-data-rest
spec:
  ports:
    - port: 8095
      name: http
  clusterIP: None
  selector:
    app: support-data-rest

---
apiVersion: v1
kind: Service
metadata:
  name: support-data-rest-http
spec:
  ports:
    - port: 30295
      targetPort: 8095
      nodePort: 30295
      protocol: TCP
  selector:
    app: support-data-rest
  type: NodePort

---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: support-data-rest-pdb
spec:
  selector:
    matchLabels:
      app: support-data-rest
  maxUnavailable: 1

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: support-data-rest
spec:
  selector:
    matchLabels:
      app: support-data-rest
  serviceName: support-data-rest-hs
  replicas: 2
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: support-data-rest
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - support-data
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: kubernetes-support-data-rest
          imagePullPolicy: Always
          image: "guoyingqi/support-data"
          resources:
            requests:
              memory: "5Gi"
              cpu: "0.5"
          ports:
            - containerPort: 8095
              name: http
          command:
            - sh
            - -c
            - "start-restful.sh \
               --zkhost=zk-0.zk-hs.default.svc.cluster.local:2181,zk-1.zk-hs.default.svc.cluster.local:2181,zk-2.zk-hs.default.svc.cluster.local:2181 \
               --log_level=INFO"
          readinessProbe:
            tcpSocket:
              port: 8095
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8095
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - name: support-rest-data
              mountPath: /var/lib/restful
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
  volumeClaimTemplates:
    - metadata:
        name: support-rest-data
      spec:
        storageClassName: nfs-client
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
